### ISSUE TITLE
the result is not same with the twitter-anomalyDetection

### ISSUE THREAD

**Issue by hongliping7** [ruananswer/twitter-anomalyDetection-java#1]
Hi,  I have use the java anomaly detection, however, the result is not same with the R anomaly detection， and I found that the result of stl decomposition is not the same, why?

**Comment by ruananswer** [comment]
Actually, the result is not the same as R anomaly detection, but is reasonable as R anomaly detection.
I will update unit test of stl and anomaly detection today, the precision is guaranteed, hope it cloud help you.
On the other hand, could you upload your results on this issues? Let us solve it!

**Comment by dhiru1990** [comment]
how to run this project..where is the main file of this program
